
name: Jekyll site CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: change directory
      run: cd site
#     - name: build
#       run: docker run --rm --volume="$PWD:/srv/jekyll" -d jekyll/builder bundle install jekyll build
    - name: build2
      run: |
        export JEKYLL_VERSION=3.8
        docker run --rm \
          --volume="$PWD:/srv/jekyll" \
          --volume="$PWD/vendor/bundle:/usr/local/bundle" \
          -it jekyll/jekyll:$JEKYLL_VERSION \
          jekyll build
