
name: Jekyll site CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Ruby for use with actions
      uses: actions/setup-ruby@v1.0.0
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
    - uses: actions/checkout@v1
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
    - name: NPM or Yarn install with caching
      uses: bahmutov/npm-install@v1.1.0
