
name: Jekyll site CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Ruby for use with actions
      uses: actions/setup-ruby@v1.0.0
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
    - uses: actions/checkout@v1
    - name: run npm build
      run: |
        cd site && gem install jekyll bundler && bundle install && npm install && npm run build
